jwt:
  secret: 1da26b2be07ec26d483b62f47e8a7129aeef99ee728e84a8278a6830cc22199e
  access:
    expiration: 3600000
    header: Authorization
  refresh:
    expiration: 1209600000
    header: Authorization-refresh

spring:
  mail:
    host: smtp.naver.com
    port: 587
    username: crystar2402@naver.com
    password: Tnwjd12118090!
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          connectiontimeout: 18000
          timeout: 18000
          writetimeout: 18000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1082732931101-ucif0lo1vb6g1e897ucvvlccf80urlji.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

          naver:
            client-id: _WxDDaC4Pf_8NgHeggZg
            client-secret: pbT0nEM8_t
            client-name: Naver
            redirect-uri: http://localhost:80/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image

          kakao:
            client-id: a6b795b0ff2013ad94fce44d5e24e0ac
            client-secret: rs1oA1Onv34xpxrapTEJh4YFGOQWU8Fa
            client-name: Kakao
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:80/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email

          github:
            client-id: Ov23liJtscVveD0HvQ6Z
            client-secret: 0165b8ae67e1a4344f032a65f053f3f63e4bbbd0
            redirect-uri: http://localhost:80/login/oauth2/code/github
            scope:
              - user:email
              - read:user

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

#client-id : 애플리케이션 등록한 후 나오는 client id
#client-secret : 애플리케이션 등록 후 나오는 client secret
#redirect-uri : 애플리케이션을 등록할 때 설정한 callback url
#provider : 서비스 제공하는 곳
#authorization-uri : 로그인 인증을 요청하는 uri
#token_uri : 접근 토큰의 발급, 갱신, 삭제를 요청하는 uri
#user-info-uri : 회원의 프로필을 조회하는 uri
#user_name_attribute : provider로부터 요청이 승인되면 출력 결과가 response의 이름을 가진 JSON으로 반환됨