jwt:
  secret: 1da26b2be07ec26d483b62f47e8a7129aeef99ee728e84a8278a6830cc22199e
  access:
    expiration: 3600000
    header: Authorization
  refresh:
    expiration: 1209600000
    header: Authorization-refresh

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1082732931101-ugmj0usjdcba1rkdq35634rkf5sdo7jl.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

          github:
            client-id: asdf
            client-secret: asdf
            scope: user:email

          naver:
            client-id: _WxDDaC4Pf_8NgHeggZg
            client-secret: MjKGFYcrft
            redirect-uri: http://localhost:80/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver

          kakao:
            client-id: 5ee4910ab0016b64a3cae150a2f92029
            client-secret: BP1YorKaNpO3QOPcgSIwutBCNlBmLBsa
            client-name: Kakao
            client-authentication-method: POST
            redirect-uri: http://localhost:80/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id